---
title: "React: Capturando erros com ErrorBoundary"
description: Usando o componente ErrorBoundary para exibir uma mensagem ou
  componente de erro amig√°vel
date: 2020-09-27 10:21:00
image: assets/img/screen-shot-2020-09-27-at-22.30.42.png
category: dev
background: "#008BF8"
---
![Desenho de uma mulher com macac√£o azul e camisa preta por baixo e um capacete amarelo, segurando uma bandeira vermelha. Atras dela tem uma pedra grande e ao lado direito dela uma pedra maior. Entre ela e a pedra do lado direito h√° uma sinaliza√ß√£o de triangulo com uma exclama√ß√£o no meio.](assets/img/screen-shot-2020-09-27-at-22.30.42.png "Desenho de uma mulher com macac√£o azul e camisa preta por baixo e um capacete amarelo, segurando uma bandeira vermelha. Atras dela tem uma pedra grande e ao lado direito dela uma pedra maior. Entre ela e a pedra do lado direito h√° uma sinaliza√ß√£o de triangulo com uma exclama√ß√£o no meio.")

\
Contexto

O projeto Base

Adicionando ErrorBoundary

Ao vivo

Refer√™ncia

Minha motiva√ß√£o e reflex√£o

## Contexto

**ErrorBoundary** no React se trata de um componente que vai ser respons√°vel por capturar erros de qualquer componente filho que lance esse erro, e quando esse erro √© capturado pode se exibir uma p√°gina de erro.

Substituir a pagina

## O projeto base:

Para o teste eu usei o mesmo projeto que fiz no post que adiciona o Loader que foi feito em CSS. Se quiser pode ver aqui esses posts:

* Criando um "loader" simples com CSS
* Exibindo um Loader para uma requisi√ß√£o no React

Mudei um pouco do projeto que fiz inicialmente somente separar um pouco os componentes.

Antes:

* No componente App.js tava criando direto um `form`
* usava um componente `UserData` para renderizar os dados do usu√°rio

Agora:

* Criei uma pasta chamada **FormUserData** em componets
* O `form` est√° num componente chamado `FormUserData.js` dentro dessa pasta
* Movi a pasta do componente **UserData** para dentro de **FormUserData**

A pasta **src** est√° basicamente assim:

```
src
‚îî‚îÄ components
|   ‚îî‚îÄ FormUserData
|	  |  ‚îî‚îÄ FormUserData.js
|   |  ‚îî‚îÄ FormUserData.css
|   |  ‚îî‚îÄ UserData
|   |     ‚îî‚îÄ UserData.js
|   |     ‚îî‚îÄ UserData.css
|   ‚îî‚îÄ Loader
‚îî‚îÄ App.js
```

E agora no **App.js** s√≥ chamo o componente **FormUserData**.

```jsx
//App.js

import React from 'react'
import FormUserData from './components/FormUserData/FormUserData'

import './App.css';

const App = () => {
  return (
    <div className="app">
       <FormUserData></FormUserData>
    </div>
  );
}

export default App;
```

Eu fiz isso pois vai me ajudar no uso do componente **ErrorBoundary**, j√° que ele pega exce√ß√µes dos filhos dele.... Vamos continuar pra entender melhor..

## Adicionando ErrorBoundary

Agora que organizei melhor o projeto conseguimos inserir o **ErrorBoundary** de forma mais organizada. Para isso precisamos:

* Criar um componente do **ErrorBoundary;**
* Colocar o componente do **ErrorBoundary** onde ele vai ser chamado quando houver erro dos componentes filhos;
* Adaptar o componente **FormUserData** para lan√ßar a exce√ß√£o;

### Criar um componente do **ErrorBoundary;**

Infelizmente o componente **ErrorBoundary** precisa ser um componente de classe. Nele precisam ser definidos um destes m√©todos de ciclo de vida:

`static getDerivedStateFromError()`: √© invocado quando um erro √© lan√ßado, recebe o erro e retorna a atualiza√ß√£o do state que vai ajudar a verifica√ß√£o para renderizar ou n√£o o erro.

Veja mais sobre esse m√©todo aqui: [](https://pt-br.reactjs.org/docs/react-component.html#static-getderivedstatefromerror)<https://pt-br.reactjs.org/docs/react-component.html#static-getderivedstatefromerror>

`componentDidCatch()`: √© invocado quando um erro √© lan√ßado e recebe dois par√¢metros que registram informa√ß√µes do erro.

1. `error` - O erro que foi lan√ßado.
2. `info` - Um objeto com informa√ß√µes sobre o componente que lan√ßou o erro.

Veja mais sobre esse m√©todo aqui: [](https://pt-br.reactjs.org/docs/react-component.html#componentdidcatch)<https://pt-br.reactjs.org/docs/react-component.html#componentdidcatch>

No meu componente optei por usar o `componentDidCatch()` pois quero uma informa√ß√£o do erro, a mensagem do throw.

```jsx
//ErrorBoundary.js

import React from "react";

class ErrorBoundary extends React.Component {
    constructor(props) {
      super(props);
      this.state = { error: null, errorInfo: null };
    }
    
    componentDidCatch(error, errorInfo) {
      this.setState({
        error: error,
        errorInfo: errorInfo
      })
    }
    
    render() {
      if (this.state.errorInfo) {
        return <h2>{this.state.error.message}</h2>
      }
      return this.props.children;
    }  
  }

export default ErrorBoundary;
```

* No construtor √© setado um state para o error e errorInfo, ambos nullo a princ√≠pio;
* O `componentDidCatch()` recebendo `error` e `errorInfo`, esse m√©todo vai ser invocado quando acontecer o erro e √© "setado" no estado de `error` e `errorInfo` o que veio no momento que o m√©todo foi invocado.
* Na fun√ß√£o de `render()` verificamos se h√° algo no state de `errorInfo` (`this.state.errorInfo`), caso haja algo (tenha chegado no `componentDidCatch()` e colocado os valores no estado deles) renderizamos nossa mensagem de erro, nesse ponto poder√≠amos tamb√©m criar um componente que seria uma p√°gina de erro amig√°vel e substituir por esse `h2`, mas quis deixar simples.
* Caso n√£o aconte√ßa nada, √© retornado o pr√≥prio componente filho.

Esse componente foi criado dentro da pasta **components**:

```
src
‚îî‚îÄ components
|   ‚îî‚îÄ ErrorBoundary
|	  |  ‚îî‚îÄ ErrorBoundary.js
|   ‚îî‚îÄ FormUserData
|	  |  ‚îî‚îÄ FormUserData.js
|   |  ‚îî‚îÄ FormUserData.css
|   |  ‚îî‚îÄ UserData
|   |     ‚îî‚îÄ UserData.js
|   |     ‚îî‚îÄ UserData.css
|   ‚îî‚îÄ Loader
‚îî‚îÄ App.js
```

### Chamar o componente ErrorBounday e colocar os filhos

Com o componente **ErrorBoundary** pronto, podemos inclui-lo onde queremos que apare√ßa o erro. No meu caso vou incluir ele no arquivo **App.js** e colocar o **FormUserData** como filho dele.

Agora App.js fica assim:

```jsx
//App.js

import React from 'react'
import FormUserData from './components/FormUserData/FormUserData'
import ErrorBoundary from './components/ErrorBoundary/ErrorBoundary'

import './App.css';

const App = () => {
  return (
    <div className="app">
      <ErrorBoundary>
        <FormUserData></FormUserData>
      </ErrorBoundary>
    </div>
  );
}

export default App;
```

> Massa! T√° pronto, √© s√≥ isso?

N√£o... Ainda precisamos fazer o componente filho FormUserData lan√ßar alguma exce√ß√£o para que o ErrorBoundary capture e exiba a mensagem/componente de erro.

### Adaptar o componente **FormUserData** para lan√ßar a exce√ß√£o

Para isso vamos no arquivo **FormUserData.js** que agora est√° dessa forma:

```jsx
import React, { useState } from 'react';
import Loader from '../Loader/Loader'
import UserData from './UserData/UserData'

import './FormUserData.css';

const FormUserData = () => {
  const [showLoader, setShowLoader] = useState(false)
  const [username, setUsername] = useState('')
  const [userData, setUserData] = useState({})


  const handleForm = (e) => {
    e.preventDefault();
    setShowLoader(true)
    fetch(`https://api.github.com/users/${username}`)
        .then(res => res.json())
        .then(data => {
          setUserData(data)
          setShowLoader(false)
        })
        .catch((err) => {
          setShowLoader(false)
        })
  }

  return (
    <>
      <form onSubmit={handleForm} className="form-github-user">
        <label htmlFor="github-user" className="label-github-user">Digite seu usu√°rio do Github:</label>
        <input type="text" id="github-user" className="input-github-user" onChange={e=>setUsername(e.target.value)}/>
        <button type="submit" className="btn-submit">Enviar</button>
      </form>
      {showLoader && <Loader/>}
			<UserData data={userData} />
		</>
  );
}

export default FormUserData;
```

E vamos adicionar a ele:

* uma vari√°vel de estado para mensagem de erro \[\`errorMessage, setErrorMessage]\`, que vai ser uma string que se **inicia vazia**;
* uma outra variavel de estado para verificar se houve erro ou n√£o `[hasError, setHasError]`, que vai ser um **boolean** que se **inicia false**;
* üö® Um `if` dentro do segundo `.then`, nele √© onde √© pego o que foi retornado da API e inserido na vari√°vel de userData. Esse `if` vai ser respons√°vel por verificar se no que foi retornado da API tem uma mensagem "**Not Found**", caso venha essa mensagem atualizamos os valores das vari√°veis `errorMessage`com a mensagem que queremos pegar e `hasError` para **true**.
* üö® Um `if` que vai fazer a verifica√ß√£o da `hasError`, caso essa vari√°vel seja **true** √© lan√ßado uma nova exce√ß√£o pegando a mensagem que foi armazenada em `errorMessage`;

O componente fica assim agora:

```jsx
import React, { useState } from 'react';
import Loader from '../Loader/Loader'
import UserData from './UserData/UserData'

import './FormUserData.css';

const FormUserData = () => {
  const [showLoader, setShowLoader] = useState(false)
  const [username, setUsername] = useState('')
	const [userData, setUserData] = useState({})
  const [hasError, setHasError] = useState(false)
  const [errorMessage, setErrorMessage] = useState('')
  
  const handleForm = (e) => {
    e.preventDefault();
    setShowLoader(true)
    fetch(`https://api.github.com/users/${username}`)
        .then(res => res.json())
        .then(data => {
          if(data.message === "Not Found") {
            setErrorMessage('Nenhum usu√°rio encontrado, recarrege a pagina')
            setHasError(true)
          }
          setUserData(data)
          setShowLoader(false)
        })
        .catch((err) => {
          setHasError(true)
          setShowLoader(false)
        })
  }

  if(hasError) {
    throw new Error(errorMessage);
  }

  const isObjectEmpty = (myObject) => {
    return Object.entries(myObject).length > 0
  }

  return (
    <>
      <form onSubmit={handleForm} className="form-github-user">
        <label htmlFor="github-user" className="label-github-user">Digite seu usu√°rio do Github:</label>
        <input type="text" id="github-user" className="input-github-user" onChange={e=>setUsername(e.target.value)}/>
        <button type="submit" className="btn-submit">Enviar</button>
      </form>
      {showLoader && <Loader/>}
      <UserData data={userData} />
    </>
  );
}

export default FormUserData;
```

## **Ao vivo**

![Gif mostrando o preenchimento do input "Digite seu usu√°rio do Github" com texto "talitaoliveira", depois clicando no bot√£o enviar e em seguida √© mostrado o resultado da buca: uma foto, e dados de nome, localiza√ß√£o, bio e dada de cria√ß√£o do perfil (informa√ß√µes retornadas do github). Em seguida √© adicionadas letras aleatorias junto ao texto digitado anteriormente, simulando um usu√°rio inexistente, depois cliando em enviar e em seguda √© mostrado uma mensagem: "Nenhum usu√°rio encontrado. Recarregue a p√°gina"](assets/img/errorboundaryexample.gif "Gif mostrando o preenchimento do input \"Digite seu usu√°rio do Github\" com texto \"talitaoliveira\", depois clicando no bot√£o enviar e em seguida √© mostrado o resultado da buca: uma foto, e dados de nome, localiza√ß√£o, bio e dada de cria√ß√£o do perfil (informa√ß√µes retornadas do github). Em seguida √© adicionadas letras aleatorias junto ao texto digitado anteriormente, simulando um usu√°rio inexistente, depois cliando em enviar e em seguda √© mostrado uma mensagem: \"Nenhum usu√°rio encontrado. Recarregue a p√°gina\"")

Como o erro √© mostrado quando n√£o encontra um usu√°rio, para testar basta adicionar um nome de usu√°rio inexistente.

Pode ser visto aqui: [](https://talitaoliveira.github.io/using-loader-wait-request-react/)<https://talitaoliveira.github.io/using-loader-wait-request-react/>

## Refer√™ncia:

[](https://pt-br.reactjs.org/docs/error-boundaries.html#gatsby-focus-wrapper)<https://pt-br.reactjs.org/docs/error-boundaries.html#gatsby-focus-wrapper>

\~üåü\~

Bem.. √© isso. üòâ

Essa semana no projeto estava com Thiago come√ßando a implementa√ß√£o da chamada da API, e Gabriel e Hugo estavam trabalhando na parte da p√°gina de erro. Como as duas partes se complementavam, precisamos ficar alinhados como estava sendo feito as duas partes para juntar depois, e eles mostraram que fizeram usando a **ErrorBoundary** e fiquei curiosa para entender melhor como funcionava, e decidi escrever sobre. üôÉ

Achei interessante, no come√ßo quando tava testando tava apanhando para fazer funcionar, e descobri que estava errando ao chamar o componente **ErrorBoundary** no mesmo componente que estava sendo lan√ßada a exce√ß√£o, da√≠ entendi que a exce√ß√£o precisa ser chamada em componentes filhos da **ErrorBoundary** (passei horas nisso, e quase desistia de postar pq n√£o tava rolando.. Mas foi.. üòõ).

Espero que este post possa ser √∫til para algu√©m üòä.

At√© a pr√≥xima. ü§ôüèΩ